export const copy = {
  greeting: {
    morning:   (name: string) => `Good morning, ${name}.`,
    afternoon: (name: string) => `Good afternoon, ${name}.`,
    evening:   (name: string) => `Good evening, ${name}.`,
    fallback:  (name: string) => `Hello, ${name}.`,
  },
  today: {
    subtitle:     'Here is your gentle plan for today.',
    noCheckIn:    'How are you feeling this morning?',
    checkInCTA:   'Start morning check-in',
    eveningCTA:   'Reflect on today',
    allDone:      'All rituals done. You showed up today.',
    aiLoading:    'Getting your daily guidance…',
  },
  lowEnergy: {
    banner:    'Low energy today. Tap to simplify.',
    headline:  "Let's make today manageable.",
    subline:   'Three small rituals. That is enough.',
    cta:       'Show me the minimum',
    rest:      'Rest is a ritual too.',
  },
  ritual: {
    complete:  'Done',
    skip:      'Rest today',
    empty:     'No rituals scheduled. Rest is a ritual too.',
    add:       'Add a ritual',
  },
  checkIn: {
    morningTitle:  'Morning check-in',
    eveningTitle:  'Evening reflection',
    saved:         'Check-in saved. Well done.',
    labels: {
      mood:             'How is your mood?',
      stress:           'How stressed do you feel?',
      anxiety:          'How anxious are you feeling?',
      cravings:         'How strong are your cravings?',
      sleepHours:       'How many hours did you sleep?',
      energy:           'How is your energy?',
      bodyPain:         'Any body discomfort today?',
      weight:           'Weight today (optional)',
      movement:         'Minutes of movement (optional)',
      foodControl:      'How was your food control?',
      spiritualPractice:'Did you have a spiritual practice today?',
      notes:            'Anything else on your mind?',
    },
    sliderMin: {
      mood:      'Low',
      stress:    'Calm',
      anxiety:   'Relaxed',
      cravings:  'None',
      energy:    'Exhausted',
      foodControl: 'Struggled',
    },
    sliderMax: {
      mood:      'Great',
      stress:    'Overwhelmed',
      anxiety:   'Anxious',
      cravings:  'Intense',
      energy:    'Energetic',
      foodControl: 'In control',
    },
  },
  coach: {
    title:     'AI Coach',
    subtitle:  'Choose what you need right now.',
    inputPlaceholder: 'Tell Ritual what is happening right now.',
    send: 'Send to coach',
    empty: 'Choose a mode or write what you need. Ritual will keep it gentle.',
    modes: {
      overthinking: 'I am overthinking',
      heavy:        'I feel heavy',
      binge:        'I want to binge eat',
      guilty:       'I feel guilty',
      sleep:        'I cannot sleep',
      nextStep:     'I need a small next step',
      motivation:   'I need motivation',
    },
    loading:  'Your coach is thinking…',
    safety:   'This sounds heavy to carry alone. Ritual can support small grounding steps, but if you feel unsafe or unable to cope, please contact a trusted person or a mental health professional.',
  },
  onboarding: {
    welcome: {
      headline: 'Rebuild your mind.\nReset your body.',
      subline:  'Small daily rituals for people who feel stuck, heavy, or overwhelmed.',
      cta:      'Begin your ritual',
      login:    'Already have an account',
    },
    steps: {
      progress: (step: number, total: number) => `Step ${step} of ${total}`,
      next:     'Continue',
      back:     'Back',
      skip:     'Skip for now',
    },
    plan: {
      loading:  'Building your ritual plan…',
      headline: 'Your plan is ready.',
      subline:  'We have created a gentle starting point based on your answers.',
      cta:      'Enter Ritual',
    },
  },
  errors: {
    generic:  'Something went wrong. Let\'s try again.',
    offline:  'You\'re offline. Changes will sync when you\'re back.',
    authFail: 'Couldn\'t sign in. Please check your details.',
    required: 'This field is required.',
  },
  auth: {
    signUp:       'Create account',
    signIn:       'Sign in',
    email:        'Email address',
    password:     'Password',
    name:         'Your first name',
    forgotPw:     'Forgot password?',
    noAccount:    'Don\'t have an account?',
    hasAccount:   'Already have an account?',
    googleSignIn: 'Continue with Google',
  },
} as const
